# Generated by Django 5.2.8 on 2025-12-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='can_export_excel_cartera',
            field=models.BooleanField(default=False, verbose_name='Puede exportar Cartera a Excel'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='can_export_pdf_cartera',
            field=models.BooleanField(default=False, verbose_name='Puede exportar Cartera a PDF'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='can_view_ajustes',
            field=models.BooleanField(default=False, verbose_name='Puede ver Ajustes'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='can_view_cartera',
            field=models.BooleanField(default=False, verbose_name='Puede ver Cartera'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='can_view_usuarios',
            field=models.BooleanField(default=False, verbose_name='Puede ver Usuarios'),
        ),
    ]
