# Generated by Django 5.2.8 on 2025-12-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useauth', '0002_perfil_can_export_excel_cartera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='can_export_all_cartera',
            field=models.BooleanField(default=False, verbose_name='Puede exportar Cartera Completa'),
        ),
    ]
