# Generated by Django 5.2.8 on 2026-05-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useauth', '0003_perfil_can_export_all_cartera'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='can_export_excel_kardex',
            field=models.BooleanField(default=False, verbose_name='Puede exportar Kardex a Excel'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='can_export_pdf_kardex',
            field=models.BooleanField(default=False, verbose_name='Puede exportar Kardex a PDF'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='can_view_kardex',
            field=models.BooleanField(default=False, verbose_name='Puede ver Kardex'),
        ),
    ]
